
spring.datasource.url=jdbc:postgresql://localhost:5432/tradeplant_db


spring.datasource.username=postgres
spring.datasource.password=258025


spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true